<?php 
  $works = array( 
              array(  'work' => 'senior_DazzlingCamoflague-1-grid',
                      'category' => 'senior all',
                      'size' => 'size-hl',
                      'sidebarswitch' => 'true',
                      'title' => 'Dazzling Camoflague',
                      'text' => '',
                      'year' => '',
                      'purpose' => '',
                      'materials' => '',
                      'dimensions' => '',
                      'process' => '',
                      'images' => array(
                        'senior_DazzlingCamoflague-1.png',
                        'senior_DazzlingCamoflague-2.png'
                      ),
                    ),
              array(  'work' => 'senior_DefensiveEnlargment-1-grid',
                      'category' => 'senior all',
                      'size' => 'size-hm',
                      'sidebarswitch' => 'true',
                      'text' => '',
                      'title' => 'Defensive Enlargement',
                      'year' => '',
                      'purpose' => '',
                      'materials' => '',
                      'dimensions' => '',
                      'process' => '',
                      'images' => array('senior_DefensiveEnlargment-1.png')
                    ),
              array(  'work' => 'senior_DistractiveDisplay-1-grid',
                      'category' => 'senior all',
                      'size' => 'size-hl',
                      'sidebarswitch' => 'true',
                      'text' => '',
                      'title' => 'Distractive Display',
                      'year' => '',
                      'purpose' => '',
                      'materials' => '',
                      'dimensions' => '',
                      'process' => '',
                      'images'=> array(
                        'senior_DistractiveDisplay-1.png',
                        'senior_DistractiveDisplay-2.png',
                        'senior_models-2.png'
                      ),
                    ),
              array(  'work' => 'senior_MethodOfAttack-1-grid',
                      'category' => 'senior all',
                      'size' => 'size-hl',
                      'sidebarswitch' => 'true',
                      'text' => '',
                      'title' => 'Method of Attack',
                      'year' => '',
                      'purpose' => '',
                      'materials' => '',
                      'dimensions' => '',
                      'process' => '',
                      'images' => array(
                        'senior_MethodOfAttack-1.png',
                        'senior_MethodOfAttack-2.png',
                        'senior_MethodOfAttack-3.png',
                        'senior_MethodOfAttack-4.png'
                      ),
                    ),
              array(  'work' => 'undergrad_cicatrix-1-grid',
                      'category' => 'undergrad wearables cuff all',
                      'size' => 'size-vm',
                      'sidebarswitch' => 'true',
                      'text' => 'Cicatrix was created after researching humans fascination with body modification. The patterning is reflective of African tribal scarification, specifically the raised cicatrix designs carved into Nilotic natives’ dermis. This piece fits onto the wearer‘s hand snuggly and suspends their index and pinky fingers straight out. This restriction also represents modification methods seen in the Mursi tribe’s lip rings, of Ethiopia, or in the neck rings of Kayan and several other African and Asian cultures. The line work was etched into the surface and contrasted with the color of a liver of sulfur patina. The piece is a formed copper sheet standing 1.5” tall by 3.5” wide.',
                      'title' => 'Cicatrix',
                      'year' => '',
                      'purpose' => 'Hand Piece',
                      'materials' => 'Copper',
                      'dimensions' => '1.5 inches tall by 3.5 inches wide',
                      'process' => 'Formed and Etched',
                      'images' => array(
                        'undergrad_cicatrix-1.png',
                        'undergrad_cicatrix-2.png'
                      ),
                    ),
              array(  'work' => 'undergrad_flowerbrooch-1-grid',
                      'category' => 'undergrad wearables brooch all',
                      'size' => 'size-vm',
                      'sidebarswitch' => 'true',
                      'text' => 'Flower Brooch 1 is the first of many flower-referencing attempts within the brooch series created for the American Craft Council tradeshow. I was working with multiple copper pieces to arrange them in a composition that was both graceful and appealing to the eye. The piece has a simple steel pin mechanism and is 5” tall by 3.5” wide.',
                      'title' => 'Flower Brooch 1',
                      'year' => '',
                      'purpose' => 'Brooch',
                      'materials' => 'Copper, Sterling Silver, and Steel',
                      'dimensions' => '5" tall by 3.5" wide',
                      'process' => 'Formed and Fabricated',
                      'images' => array('undergrad_flowerbrooch-1.png')
                    ),
              array(  'work' => 'undergrad_flowerbrooch-2-grid',
                      'category' => 'undergrad wearables brooch all',
                      'size' => 'size-vm',
                      'sidebarswitch' => 'true',
                      'text' => 'Flower Brooch 2 is another brooch from the flower brooch series that was displayed at the American Craft Council tradeshow. I had trouble finding a way that these formed copper pieces could elegantly join together. After a while I discovered that if wedged correctly they nestled into one another like puzzle pieces. The smaller size helps emphasize the quick peek of beauty that can be presented by the wearer. The brooch is 2.5” tall by 2.5” wide.',
                      'title' => 'Flower Brooch 2',
                      'year' => '',
                      'purpose' => 'Brooch',
                      'materials' => 'Copper, Sterling Silver, and Steel',
                      'dimensions' => '2.5" tall by 2.5" wide',
                      'process' => 'Formed and Fabricated',
                      'images' => array('undergrad_flowerbrooch-2.png')
                    ),
              array(  'work' => 'undergrad_medusa-grid',
                      'category' => 'undergrad vase all',
                      'size' => 'size-vl',
                      'sidebarswitch' => 'true',
                      'text' => 'The Medusa Vessel was inspired by the Greek Mythology tale of Medusa. Legend has it the beautiful gorgon with flowing locks was taken advantage of in Athena’s temple by Poseidon. Athena punished Medusa for the desecration of her temple by turning her into a frightening, snake-headed monster whose sight petrified any living thing into stone. The Medusa Vessel is 4.5” tall by 2.5” wide. It started out as a 16 gauge sheet of copper and was raised over a variety of stakes until it reached the desired shape. This vessel represents the transformation experienced while Medusa changed from gorgeous to hideous.',
                      'title' => 'Medusa',
                      'year' => '',
                      'purpose' => 'Vessel',
                      'materials' => 'Copper',
                      'dimensions' => '4.5" tall by 2.5" wide',
                      'process' => 'Raised, Chased, Patina',
                      'images' => array('undergrad_medusa.png')
                    ),
              array(  'work' => 'undergrad_olio-grid',
                      'category' => 'undergrad wearables brooch all',
                      'size' => 'size-vl',
                      'sidebarswitch' => 'true',
                      'text' => 'Olio was the first of many brooches that grew out of the exploration of anticlastic and synclastic metalsmithing. This was made for the ACC show in 2012 and before its creation was nothing but a hefty deadline approaching. I had been working on several experiments for an upcoming photo shoot and not a single thing was coming together. The day before the shoot my professor scratched everything I had been working on and this organic form blossomed overnight. Olio, also known as the 8 hour brooch, is a combination of formed copper sheet and forged copper and sterling silver rod. The form is 4” tall by 4.5” wide. The surface decoration is etched and darkened with a liver of sulfur patina. ',
                      'title' => 'Olio',
                      'year' => '',
                      'purpose' => 'Brooch',
                      'materials' => 'Copper, Sterling Silver',
                      'dimensions' => '',
                      'process' => 'Formed and Etched',
                      'images' => array('undergrad_olio.png')
                    ),
              array(  'work' => 'undergrad_decadentdining-grid',
                      'category' => 'undergrad all',
                      'size' => 'size-vm',
                      'sidebarswitch' => 'true',
                      'text' => 'Decadent Dessert Dining is a pair of forged cutlery. This set was created to enhance and exaggerate the act of eating dessert. The sensually elongated handles of the flat ware make the dessert bite travel longer from the plate, building anticipation, until it reaches the enjoyer’s mouth. The fork and spoon started out as 3” long by .75” wide copper rods and were forged to the elongated shape of 8.5” long by 1” wide. They were finished with etching accents that where silver plated for functionality.',
                      'title' => 'Decadent Dining',
                      'year' => '',
                      'purpose' => 'Cutlery',
                      'materials' => 'Copper',
                      'dimensions' => '8.5" long by 1" wide',
                      'process' => 'Forged and Silver Plated',
                      'images' => array('undergrad_decadentdining.png')
                    ),
              array(  'work' => 'undergrad_weaponofdefensedepression-grid',
                      'category' => 'undergrad all',
                      'size' => 'size-vl',
                      'sidebarswitch' => 'true',
                      'text' => 'Weapon Of Defense: Depression, is a piece that expresses the over powering control melancholic thoughts can have on ones ability to live a healthy life. The steel black wire exposes how depression can grow from a few small internal thoughts and quickly overtake the exterior. The wrapping, twisting, and tangling represent the devastating effects these feelings can have on the body of an individual. This vessel is seamed instead of raised as an experimental substitute in creating volume by an unfamiliar means. The surface decoration is chased and colored with a heat patina, standing 8.5” tall by 5” wide.',
                      'title' => 'Weapon of Defense: Depression',
                      'year' => '',
                      'purpose' => 'Vessel',
                      'materials' => 'Copper and Steel',
                      'dimensions' => '8.5" tall by 5" wide',
                      'process' => 'Fabricated and Seamed',
                      'images' => array('undergrad_weaponofdefensedepression.png')
                    ),

              array(  'work' => 'undergrad_menneednotapply-1-grid',
                      'category' => 'undergrad all',
                      'size' => 'size-vm',
                      'sidebarswitch' => 'true',
                      'text' => 'Men Need Not Apply was a piece created out of sheer heartbreak, frustration, and anger, spawned by a member of the opposite sex. The locket hits right where the heart rests to represent the need to protect oneself. Men Need Not Apply is a reminder to never allow someone access to your soul. Someone turned mine black once because I allowed him to and never will I allow that to happen again. The locket component is a copper sheet that has been hydraulic dye formed. The neck wire is forged copper rod and the coloring is a liver of sulfur patina. The piece is about 12” long by 5” wide.',
                      'title' => 'Men Need Not Apply',
                      'year' => '',
                      'purpose' => 'Locket Necklace',
                      'materials' => 'Copper',
                      'dimensions' => '12" tall by 5" wide',
                      'process' => 'Hydraulic Dye Formed, Forged, and Fabricated',
                      'images' => array('undergrad_menneednotapply-1.png','undergrad_menneednotapply-2.png')
                    ),
              array(  'work' => 'undergrad_hotglue-1-grid',
                      'category' => 'undergrad wearables ring all',
                      'size' => 'size-vm',
                      'sidebarswitch' => 'true',
                      'text' => 'Height Via Hot Glue is a hollow construction ring that allowed me to experiment with alternative materials in an untraditional fashion. I was working on a separate project adjacent to this one that involved hot glue and while dealing with the stringy molten glue, I began to play with the insistent flyaway strings that had originally upset me. Volume was found while playing and instantly the topper for the ring was discovered. The ring is about 1” tall by 1” wide with a hot glue pile towering at 2.5” tall.',
                      'title' => 'Height Via Hot Glue',
                      'year' => '',
                      'purpose' => 'Ring',
                      'materials' => 'Sterling Silver and Hot Glue',
                      'dimensions' => '3.5" tall by 1" wide',
                      'process' => 'Forming, Fabrication, and Hot Gluing',
                      'images' => array(
                        'undergrad_hotglue-1.png',
                        'undergrad_hotglue-2.png'
                      ),
                    ),
              array(  'work' => 'undergrad_polyps-1-grid',
                      'category' => 'undergrad all',
                      'size' => 'size-vl',
                      'sidebarswitch' => 'true',
                      'text' => 'Polypsy is a headpiece based off the growth of organic materials over other existing organisms. Mushrooms, vines, and Spanish moss all grow onto other structures, otherwise they would not survive. This piece is an exaggerated example of this creeping growth happening to the human physic. This concept merged from creating work to adorn the body in unexpected ways and incorporating the techniques of casting and forging. Polypsy restricts the movement of the wearer’s head, neck, and shoulder regions reaching 1.25’ tall and 1’ wide.',
                      'title' => 'Polypsy',
                      'year' => '',
                      'purpose' => 'Headpiece',
                      'materials' => 'Copper and Yellow Bronze',
                      'dimensions' => '1.25" tall by 1" wide',
                      'process' => 'Cast and Forged',
                      'images' => array(
                        'undergrad_polyps-1.png',
                        'undergrad_polyps-2.png'
                      ),
                    ),
              array(  'work' => 'undergrad_dino-grid',
                      'category' => 'undergrad wearables ring all',
                      'size' => 'size-hm',
                      'sidebarswitch' => 'true',
                      'text' => 'Dino is a hollow construction ring that was one of those challenging learning experiences. I was very frustrated while creating it but learned a lot about fabrication. Originally the ring was supposed to give the impression that it was from the moon with certain stamping designs on the brass but when the final piece came to a conclusion it more closely resembled a dinosaur and that is how this ring got its name. There are five bezel set moonstones that flow along the spine of the ring and the body was fabricated out of brass and sterling silver sheet. The ring fits a size 8.5 and is .75” wide by 1” tall. ',
                      'title' => 'Dino',
                      'year' => '',
                      'purpose' => 'Ring',
                      'materials' => 'Sterling Silver, Brass, and Moon Stones',
                      'dimensions' => '1" tall by .75" wide',
                      'process' => 'Hollow Construction',
                      'images' => array(
                        'undergrad_dino.png'
                      ),
                    ),
              array(  'work' => 'undergrad_puffbrooch-grid',
                      'category' => 'undergrad wearables brooch all',
                      'size' => 'size-vm',
                      'sidebarswitch' => 'true',
                      'text' => 'Puff Brooch is a toned down, small piece based off my senior collection but made for the American Craft Council tradeshow in Atlanta, Georgia 2012. It is a wearable brooch that utilizes explorative forming techniques from the Animal Takeover series but on a smaller scale. It is a single piece of formed copper with sewn rabbit fur filling the center. Puff Brooch is 2.5” wide by 3” tall.',
                      'title' => 'Puff Brooch',
                      'year' => '',
                      'purpose' => 'Brooch',
                      'materials' => 'Copper, Steel, and Rabbit Fur',
                      'dimensions' => '2.5" wide by 3" tall',
                      'process' => 'Hollow Construction',
                       'images' => array(
                        'undergrad_puffbrooch.png'
                      ),
                    ),
              array(  "work" => 'undergrad_rendition-1-grid',
                      "category" => 'undergrad wearables cuff all',
                      "size" => 'size-hl',
                      'sidebarswitch' => 'true',
                      'text' => 'Domed Rendition II is a remake of the very first project from my introduction to jewelry class. This was an interesting experiment because it utilized my unique original form and allowed me to push the design further to show the artist I have grown into three years later. I formed the lining the cuff to give it a more graceful edge and etched the surface to accent the riveted brass “hands”. This piece is formed out of copper and is 3” tall by 6” wide.',
                      'title' => 'Domed Rendition',
                      'year' => '',
                      'purpose' => 'Cuff',
                      'materials' => 'Copper and Brass',
                      'dimensions' => '3" tall by 6" wide',
                      'process' => 'Formed and Etched',
                      'images' => array(
                        'undergrad_rendition-1.png',
                        'undergrad_rendition-2.png',
                        'undergrad_rendition-3.png'
                        )
                      ),
              array(  'work' => 'undergrad_earring-wobbly-grid',
                      'category' => 'wearables undergrad earrings all',
                      'size' => 'size-vm',
                      'sidebarswitch' => 'true',
                      'title' => 'Wobbly Earrings',
                      'text' => 'The Wobbly earrings are the twin sisters of the untitled earrings. They are the continued product of the identical multiple rubber mold experiment. The change in color not only transforms the look and flow of the set but also exhibits the different product that can be created from the same form. This pair was cast in sterling silver and is .75” wide by 1” tall.',
                      'year' => '',
                      'purpose' => 'Earrings',
                      'materials' => 'Sterling Silver',
                      'dimensions' => '1" tall by .75" wide',
                      'process' => 'Rubber mold injection and Lost wax casting ',
                      'images' => array('undergrad_earring-wobbly.png')
                    ),
              array(  'work' => 'undergrad_earring-untitiled-1-grid',
                      'category' => 'wearables undergrad earrings all',
                      'size' => 'size-vl',
                      'sidebarswitch' => 'true',
                      'title' => 'Untitled',
                      'text' => 'These untitled earrings were created while I was learning to carve blue wax. I was working with making rubber injection molds and wanted to make an earring that was reversible and multifaceted. Rubber molds are good for quick identical multiples and the way these earrings were carved it allowed the ear wire to simply be bent one way and the second the other and they are identical. This pair was cast in yellow bronze and are .75” wide by 1 tall”.',
                      'year' => '',
                      'purpose' => 'Earrings',
                      'materials' => 'Yellow Bronze',
                      'dimensions' => '1" tall by .75" wide',
                      'process' => 'Lost wax casting',
                      'images' => array('undergrad_earring-untitiled-1.png','undergrad_earring-untitled-2.png', 'senior_models-3.png')
                    ),
              array(  'work' => 'undergrad_forgedbeauty-grid',
                      'category' => 'wearables undergrad necklace all',
                      'size' => 'size-vl',
                      'sidebarswitch' => 'true',
                      'title' => 'Forged Beauty',
                      'text' => 'Forged Beauty is the first attempt I made at forging steel.  I wanted to create a piece that would hang from the wearers back and had repeated shapes all relying on one another in order to function. Each piece is its own separate hook but once connected together they create a graceful descending piece of jewelry. The steel is paired with brass for the nice contrast in color and is 1.75’ long by 9” wide.',
                      'year' => '',
                      'purpose' => 'Back Piece',
                      'materials' => 'Steel and Brass',
                      'dimensions' => '1.75’ long by 9” wide',
                      'process' => 'Forged',
                      'images' => array('undergrad_forgedbeauty.png')
                    ),
              array(  'work' => 'undergrad_roach-1-grid',
                      'category' => 'wearables undergrad Head-piece all',
                      'size' => 'size-vl',
                      'sidebarswitch' => 'true',
                      'title' => 'Splat',
                      'text' => 'Splat was an experimental casting piece. I was toying with the idea of contrast, specifically that ugly can be beautiful. Casting cockroaches seemed to be the first thing that came to mind because they are considered hideous, are free, and they are everywhere in Savannah. I love the reaction viewers have once they take a closer glance and realize the pieces are actual cast cockroaches. They often become grossed out after having been drawn in by the form and wild coloring. Splat is a headpiece that was created using several different processes. The cockroaches where found and cast in sterling silver, the splatter is a variety of different bronzes collected from a casting machine after they had been abandoned, which were then fused together, and the cap is a domed sheet of brass that has been etched. The piece is 9” long x 5.5” wide and the coloring is a heat patina.',
                      'year' => '',
                      'purpose' => 'Head Piece',
                      'materials' => 'Sterling Silver, Copper, Bronze, Brass',
                      'dimensions' => '9" long by 5.5" wide',
                      'process' => 'Cast, Formed, Forged, and Etched',
                      'images' => array('undergrad_roach-1.png','undergrad_roach-2.png')
                    ),
              array(  'work' => 'undergrad_lantern-1-grid',
                      'category' => 'wearables undergrad necklace all',
                      'size' => 'size-vl',
                      'sidebarswitch' => 'true',
                      'title' => 'Soul',
                      'text' => 'Soul is a piece that was created as a representation of my being. “I am a mind, body, and soul expression. With my mind interconnected, expansive, and always changing like wire. My body beautiful, tough, and protective but imperfect like formed brass. And my soul, as bright as a light in the darkness but as easily lit as is blown out.” The piece is meant to be seen lit in a very dark room and when it is, it fills the room with a warm comforting ambiance. Soul is a hanging lantern bracelet that S-hooks around the wrist and is 7” wide by 7” long. It is made from copper and brass wire, domed copper, and a white bronze cast candle pedestal.',
                      'year' => '',
                      'purpose' => 'Locket Necklace',
                      'materials' => 'Copper, Bronze, and Brass',
                      'dimensions' => '7" long by 7" wide',
                      'process' => 'Formed, Fabricated, and Cast',
                      'images' => array('undergrad_lantern-1.png','undergrad_lantern-2.png')
                    ),
              array(  "work" => 'wearables_earring-fur-1-grid',
                      "category" => 'wearables earring all',
                      "size" => 'size-vm',
                      'images' => array(
                        'wearables_earring-fur-1.png',
                        'wearables_earring-fur-2.png',
                        'wearables_earring-fur-3.png',
                        'wearables_earring-fur-4.png'
                      ),
                    ),
              array(  "work" => 'crocbite-1-grid',
                      "category" => 'guitar all',
                      "size" => 'size-hm',
                      'images' => array(
                        'crocbite-1.png',
                        'crocbite-2.png',
                        'crocbite-3.png',
                        'crocbite-4.png',
                        'crocbite-5.png'
                      ),
                    ),
              array(  "work" => 'wearables_sydney-1-grid',
                      "category" => 'wearables ring all',
                      "size" => 'size-vs',
                      'images' => array(
                        'wearables_sydney-1.png',
                        'wearables_sydney-2.png',
                        'wearables_sydney-3.png',
                        'wearables_sydney-4.png',
                        'wearables_sydney-5.png',
                        'wearables_sydney-6.png',
                        'wearables_sydney-7.png',
                        'wearables_sydney-8.png',
                        'wearables_sydney-9.png',
                        'wearables_sydney-10.png'
                      ),
                    ),
              array(  'work' => 'wearables_earring-shell-grid',
                      'category' => 'wearables earring all',
                      'size' => 'size-hs',
                      'images' => array('wearables_earring-shell.png')
                    ),
              array(  'work' => 'wearables_necklace-owl-grid',
                      'category' => 'wearables necklace all',
                      'size' => 'size-hs',
                      'images' => array('wearables_necklace-owl.png')
                    ),
              array(  'work' => 'wearables_ring-spiral-grid',
                      'category' => 'wearables ring all',
                      'size' => 'size-hs',
                      'images' => array('wearables_ring-spiral.png')
                    ),
              array(  'work' => 'wearables_ring-geometric-grid',
                      'category' => 'wearables ring all',
                      'size' => 'size-hs',
                      'images' => array('wearables_ring-geometric.png')
                    ),
              array(  'work' => 'wearables_ring-bluestone-grid',
                      'category' => 'wearables ring all',
                      'size' => 'size-hs',
                      'images' => array('wearables_ring-bluestone.png')
                    ),
              array(  'work' => 'wearables_earring-brokenheart-1-grid',
                      'category' => 'wearables earring all',
                      'size' => 'size-vm',
                      'images' => array('wearables_earring-brokenheart-1.png','wearables_earring-brokenheart-2.png')
                    ),
              array(  'work' => 'wearables_cuff-geometric-grid',
                      'category' => 'wearables cuff all',
                      'size' => 'size-vs',
                      'images' => array('wearables_cuff-geometric.png')
                    ),
              array(  'work' => 'wearables_cuff-heartbeat-grid',
                      'category' => 'wearables cuff all',
                      'size' => 'size-hs',
                      'images' => array('wearables_cuff-heartbeat.png')
                    ),
              array(  'work' => 'wearables_earring-heartbeat-grid',
                      'category' => 'wearables earring all',
                      'size' => 'size-vm',
                      'images' => array('wearables_earring-heartbeat.png')
                    ),
              array(  'work' => 'wearables_cuff-swirl-grid',
                      'category' => 'wearables cuff all',
                      'size' => 'size-ls',
                      'images' => array('wearables_cuff-swirl.png')
                    ),
              array(  'work' => 'wearables_earring-long-1-grid',
                      'category' => 'wearables cuff all',
                      'size' => 'size-vs',
                      'images' => array('wearables_earring-long-1.png','wearables_earring-long-2.png')
                    ),
              array(  'work' => 'wearables_earring-oval-grid',
                      'category' => 'wearables cuff all',
                      'size' => 'size-vs',
                      'images' => array('wearables_earring-oval.png')
                    ),
              array(  'work' => 'wearables_earring-vagina-grid',
                      'category' => 'wearables earrings all',
                      'size' => 'size-vs',
                      'images' => array('wearables_earring-vagina.png')
                    ),
              array(  'work' => 'wearables_earring-vulva-grid',
                      'category' => 'wearables earring all',
                      'size' => 'size-hm',
                      'images' => array('wearables_earring-vulva.png')
                    ),
              array(  'work' => 'wearables_tag-cheetoh-grid',
                      'category' => 'wearables tag all',
                      'size' => 'size-hs',
                      'images' => array('wearables_tag-cheetoh.png')
                    ),
              array(  'work' => 'wearables_tag-tree-grid',
                      'category' => 'wearables tag all',
                      'size' => 'size-hs',
                      'images' => array('wearables_tag-tree.png')
                    ),
              array(  "work" => 'wearables_tag-swirl-grid',
                      'category' => 'wearables tag all',
                      'size' => 'size-hs',
                      'images' => array('wearables_tag-swirl.png')
                    ),
              array(  'work' => 'painting_nyc_2015-01-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs',
                      'images' => array('painting_nyc_2015-01.png')
                    ),
              array(  'work' => 'painting_nyc_2015-02-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs',
                      'images' => array('painting_nyc_2015-02.png')
                    ),
              array(  'work' => 'painting_nyc_2015-03-grid',
                      'category' => 'paintings all',
                      'size' => 'size-hm',
                      'images' => array('painting_nyc_2015-03.png')
                    ),
              array(  'work' => 'painting_nyc_2015-04-grid',
                      'category' => 'paintings all',
                      'size' => 'size-hl',
                      'images' => array('painting_nyc_2015-04.png')
                    ),
              array(  'work' => 'painting_nyc_2015-05-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs',
                      'images' => array('painting_nyc_2015-05.png')
                    ),
              array(  'work' => 'painting_nyc_2015-06-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vl',
                      'images' => array('painting_nyc_2015-06.png')
                    ),
              array(  'work' => 'painting_nyc_2015-07-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs',
                      'images' => array('painting_nyc_2015-07.png')
                    ),
              array(  'work' => 'painting_nyc_2015-08-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vm',
                      'images' => array('painting_nyc_2015-08.png')
                    ),
              array(  'work' => 'painting_nyc_2015-09-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vm',
                      'images' => array('painting_nyc_2015-09.png')
                    ),
              array(  'work' => 'painting_nyc_2015-10-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs-hm',
                      'images' => array('painting_nyc_2015-10.png')
                    ),
              array(  'work' => 'painting_nyc_2015-11-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs-hm',
                      'images' => array('painting_nyc_2015-11.png')
                    ),
              array(  'work' => 'painting_nyc_2015-12',
                      'category' => 'paintings all',
                      'size' => 'size-vm-hs',
                      'images' => array('painting_nyc_2015-12.png')
                    ),
              array(  'work' => 'painting_nyc_2015-13-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs',
                      'images' => array('painting_nyc_2015-13.png')
                    ),
              array(  'work' => 'painting_nyc_2015-14-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vm',
                      'images' => array('painting_nyc_2015-14.png')
                    ),
              array(  'work' => 'painting_nyc_2015-15-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs',
                      'images' => array('painting_nyc_2015-15.png')
                    ),
              array(  'work' => 'painting_nyc_2015-16-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs',
                      'images' => array('painting_nyc_2015-16.png')
                    ),
              array(  'work' => 'painting_nyc_2015-17-grid',
                      'category' => 'paintings all',
                      'size' => 'size-vs',
                      'images' => array('painting_nyc_2015-17.png')
                    )
              );
?>